### ISSUE TITLE
macrosPlugin is not a function

### ISSUE THREAD

**Issue by cdauth** [itsMapleLeaf/vite-plugin-babel-macros#8]
I'm trying to use macrosPlugin in an NPM module that has `"type": "module"` set in its `package.json`. When I'm trying to use macrosPlugin like in the instructions, I get an error `macrosPlugin is not a function`. I can fix it by using `macrosPlugin.default()`, although then the type definitions do not match anymore.

With the fixed usage, the dev server starts, but my web app fails to load and shows the error `[plugin:babel-macros] [...].ts: Cannot use import statement outside a module`.

**Comment by itsMapleLeaf** [comment]
Thanks for reporting this! I took the opportunity to modernize the project, and this should be fixed in v1.0.6

**Comment by cdauth** [comment]
Thanks for the quick reaction. I can properly import the macros plugin now.

The error `Cannot use import statement outside a module` was not fixed by this. I found out that the error was caused by the fact that I had a file called `macro.ts` in my code, which Babel thought was a Babel Macro. I fixed the error by renaming that file.

Afterwards the styled-components macro that I wanted to use still didn't work due to styled-components/styled-components#3635. I solved the problem by upgrading styled-components to the latest version.
